# Generated by Django 5.1.1 on 2024-09-12 01:09

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_categoria_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(default=myapp.models.get_current_date),
        ),
    ]
