# Generated by Django 5.1.1 on 2024-09-12 01:14

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_venta_fecha_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateTimeField(default=myapp.models.get_current_date),
        ),
    ]
